"""Deep network stack audit (DNS, resolv.conf, routing)."""

# nordctl-src-id:NCTL-src-a7f3c912-6e4b-5d8a

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

from nordctl import network_linux as net


def _run(argv: list[str], timeout: float = 8.0) -> tuple[bool, str]:
    try:
        r = subprocess.run(argv, capture_output=True, text=True, timeout=timeout)
        return r.returncode == 0, ((r.stdout or "") + (r.stderr or "")).strip()
    except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
        return False, str(exc)


def resolv_conf_path() -> Path:
    return Path("/etc/resolv.conf")


def check_resolv_conf() -> dict[str, Any]:
    path = resolv_conf_path()
    fixes: list[str] = []
    ok = True
    summary = "resolv.conf looks normal"
    detail: dict[str, Any] = {"path": str(path)}

    if not path.exists():
        return {"ok": False, "summary": "resolv.conf missing", "fix": ["Reboot or restart NetworkManager"], "detail": detail}

    try:
        target = os.readlink(path) if path.is_symlink() else None
    except OSError:
        target = None
    detail["symlink"] = target
    content = path.read_text(encoding="utf-8", errors="replace")
    detail["head"] = content.splitlines()[:8]
    detail["nord_generated"] = "# Generated by NordVPN" in content
    detail["immutable"] = _is_immutable(path)

    if detail["immutable"]:
        ok = False
        summary = "resolv.conf is immutable (chattr +i)"
        fixes.append("sudo chattr -i /etc/resolv.conf")
        fixes.append("Then reconnect WiFi or: sudo systemctl restart systemd-resolved NetworkManager")

    if detail["nord_generated"] and not target:
        ok = False
        summary = "resolv.conf still shows NordVPN DNS while possibly disconnected"
        fixes.append("nordvpn disconnect")
        fixes.append("sudo systemctl restart systemd-resolved")
        fixes.append("If stuck: sudo chattr -i /etc/resolv.conf && edit or symlink to systemd stub")

    stub = "/run/systemd/resolve/stub-resolv.conf"
    if not target and path.is_file() and not detail["nord_generated"]:
        ok = False
        summary = "resolv.conf is a plain file (not systemd stub symlink)"
        fixes.append(f"sudo ln -sf {stub} /etc/resolv.conf")
        fixes.append("sudo systemctl restart systemd-resolved NetworkManager")

    return {"ok": ok, "summary": summary, "fix": fixes, "detail": detail}


def _is_immutable(path: Path) -> bool:
    ok, out = _run(["lsattr", str(path)])
    if not ok:
        return False
    return "i" in out.split()[0] if out.split() else False


def check_dns_manager() -> dict[str, Any]:
    fixes: list[str] = []
    ok, resolve_out = _run(["resolvectl", "status"])
    detail = {"resolvectl": resolve_out[:2000] if resolve_out else ""}
    if not ok:
        return {
            "ok": False,
            "summary": "systemd-resolved not responding",
            "fix": ["sudo systemctl enable --now systemd-resolved"],
            "detail": detail,
        }
    nm_conf = Path("/etc/NetworkManager/conf.d")
    nord_nm = list(nm_conf.glob("*nord*")) if nm_conf.is_dir() else []
    detail["nord_nm_confs"] = [str(p) for p in nord_nm]
    summary = "DNS manager active (resolvectl)"
    if nord_nm and "DNSOverTLS" not in resolve_out:
        summary = "NetworkManager Nord DNS snippets present"
    return {"ok": True, "summary": summary, "fix": fixes, "detail": detail}


def check_ipv6() -> dict[str, Any]:
    ok6 = False
    try:
        txt = Path("/proc/sys/net/ipv6/conf/all/disable_ipv6").read_text(encoding="utf-8").strip()
        ok6 = txt == "0"
    except OSError:
        pass
    why = (
        "IPv6 traffic can bypass an IPv4-only VPN tunnel and leak your real address or DNS. "
        "Disabling IPv6 system-wide is a common hardening step for strict VPN users."
    )
    return {
        "ok": not ok6,
        "summary": "IPv6 enabled (may bypass VPN)" if ok6 else "IPv6 disabled globally",
        "fix": [
            why,
            "Use top bar Wizard → Disable IPv6 (needs sudo), or run: sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1",
        ] if ok6 else [],
        "detail": {"ipv6_enabled": ok6, "why": why},
        "severity": "warning" if ok6 else "ok",
        "action": "disable_ipv6" if ok6 else None,
    }


def fix_resolv_stub() -> dict[str, Any]:
    from nordctl.privileges import run_privileged

    stub = "/run/systemd/resolve/stub-resolv.conf"
    steps: list[dict[str, Any]] = [
        run_privileged(["ln", "-sf", stub, "/etc/resolv.conf"], timeout=15),
        run_privileged(["systemctl", "restart", "systemd-resolved"], timeout=30),
        run_privileged(["systemctl", "restart", "NetworkManager"], timeout=30),
    ]
    ok = all(s.get("ok") for s in steps)
    needs_pw = any(s.get("needs_password") for s in steps)
    manual = f"sudo ln -sf {stub} /etc/resolv.conf && sudo systemctl restart systemd-resolved NetworkManager"
    return {
        "ok": ok,
        "steps": steps,
        "needs_password": needs_pw,
        "manual": manual,
        "note": "Linked resolv.conf to systemd stub" if ok else ("Run in terminal: " + manual if needs_pw else "Failed to fix resolv.conf"),
    }


def disable_ipv6() -> dict[str, Any]:
    from nordctl.privileges import run_privileged

    steps: list[dict[str, Any]] = []
    for key in (
        "net.ipv6.conf.all.disable_ipv6",
        "net.ipv6.conf.default.disable_ipv6",
        "net.ipv6.conf.lo.disable_ipv6",
    ):
        steps.append(run_privileged(["sysctl", "-w", f"{key}=1"], timeout=10))
    ok = all(s.get("ok") for s in steps)
    manual = "sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 net.ipv6.conf.default.disable_ipv6=1 net.ipv6.conf.lo.disable_ipv6=1"
    needs_pw = any(s.get("needs_password") for s in steps)
    return {
        "ok": ok,
        "steps": steps,
        "needs_password": needs_pw,
        "manual": manual,
        "note": "IPv6 disabled" if ok else ("Run in terminal: " + manual if needs_pw else "Failed to disable IPv6"),
    }


def check_connectivity() -> dict[str, Any]:
    ping_ok, ping_out = _run(["ping", "-c", "1", "-W", "2", "1.1.1.1"], timeout=5)
    dns_ok, dns_out = _run(["getent", "hosts", "cloudflare.com"], timeout=5)
    ok = ping_ok and dns_ok
    fixes: list[str] = []
    if not ping_ok:
        fixes.append("No ICMP to 1.1.1.1 — check VPN kill switch or routing")
    if not dns_ok:
        fixes.append("DNS resolution failed — run Leak Lab and check resolv.conf")
    return {
        "ok": ok,
        "summary": "Internet + DNS resolution OK" if ok else "Connectivity or DNS problem",
        "fix": fixes,
        "detail": {"ping": ping_ok, "dns": dns_ok, "ping_out": ping_out[:200], "dns_out": dns_out[:200]},
    }


def route_check(target: str = "8.8.8.8") -> dict[str, Any]:
    ok, out = _run(["ip", "route", "get", target])
    via_vpn = "nordlynx" in out.lower() if out else False
    return {"ok": ok, "target": target, "via_vpn": via_vpn, "output": out}


def run_network_audit() -> dict[str, Any]:
    checks = [
        {"id": "resolv_conf", **check_resolv_conf()},
        {"id": "dns_manager", **check_dns_manager()},
        {"id": "ipv6", **check_ipv6()},
        {"id": "connectivity", **check_connectivity()},
    ]
    for c in checks:
        if "severity" not in c:
            c["severity"] = "ok" if c.get("ok") else "error"
    blocking = sum(1 for c in checks if not c["ok"] and c.get("severity") == "error")
    return {"ok": blocking == 0, "checks": checks, "route_sample": route_check()}
